title: Page

icon: 📝

options:
  delete: false
  changeTitle: false
  changeStatus: false
  duplicate: false

# # Page presets are a quick way to set up a standard page layout
# # More about page presets:
# # - https://getkirby.com/docs/guide/blueprints/presets and
# # - https://getkirby.com/docs/reference/panel/presets/page
# preset: page

# # Custom descriptions of page statuses depending on use case
# # More about page statuses: https://getkirby.com/docs/reference/panel/blueprints/page#statuses
# status:
#   draft: true
#   unlisted:
#     label: Hidden Page
#     text: The page is not listed in the main menu
#   listed:
#     label: Menu Page
#     text: The page is listed in the main menu

# Limit subpage display to certain templates in a page preset
pages:
  template: default
# pages: false

fields:
  title:
    label: Title
    type:  text

  text:
    label: Text
    type:  textarea
