title: Site

columns:
  - width: 1/3
    sections:
      pages:
        type: pages
        create: false
        templates:
          - home
          - about
          - farm
          - brewery
          - blog
          - shop
          - error

  - width: 1/3
    fields:
      address:
        label: Address
        type: textarea
      email:
        label: Email
        type: email
      phone:
        label: Phone
        type: tel
      fax:
        label: Fax
        type: tel
  - width: 1/3
    fields:
      instagram:
        label: Instagram
        type: text
      youtube:
        label: YouTube
        type: text
      facebook:
        label: Facebook
        type: text
      linkedin:
        label: LinkedIn
        type: text
      twitter:
        label: Twitter
        type: text

      separator:
        type: line

      paypalEnabled:
        label: Paypal
        type: select
        options:
          - enabled
          - disabled

# fields:

#   metaDescription:
#     label: Meta description
#     type:  text
#     width: 1/2
#   metaKeywords:
#     label: Meta keywords
#     type:  text
#     width: 1/2

#   separator:
#     type: line

#   warning:
#     type: info
#     text: >
#       WARNING: disabling the website will hide all pages. No content will be deleted.
#   disabled:
#     label: Disable website?
#     type: toggle
#     width: 2/4
#   sorry:
#     label: Offline message
#     type: text
#     width: 3/4
